
server:
  port: 9996

spring:
  datasource:
    username: root
    password: ganxianhong2012
    url: jdbc:mysql://localhost:3306/bbs?serverTimezone=GMT%2B8



  redis:
    port: 6379
    host: 124.221.138.245

